// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsk.Saml.IdentityProvider.Storage.EntityFramework.DbContexts;

#nullable disable

namespace OpenIddictIdP.Data.Migrations.SamlConfiguration
{
    [DbContext(typeof(SamlConfigurationDbContext))]
    [Migration("20250707141940_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ArtifactResolutionService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderArtifactResolutionServices", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.AssertionConsumerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderAssertionConsumerServices", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SamlClaimMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewClaimType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalClaimType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderClaimMappings", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowIdpInitiatedSso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactDeliveryBindingType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EncryptAssertions")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EncryptionCertificate")
                        .HasColumnType("BLOB");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameIdentifierFormat")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RequireAuthenticationRequestsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireSamlMessageDestination")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RequireSignedArtifactResolveRequests")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RequireSignedArtifactResponses")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SignAssertions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SigningCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Certificate")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderSignCertificates", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SingleLogoutService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderSingleLogoutServices", (string)null);
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ArtifactResolutionService", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("ArtifactResolutionServices")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.AssertionConsumerService", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("AssertionConsumerServices")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SamlClaimMap", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("ClaimsMapping")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SigningCertificate", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("SigningCertificates")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.SingleLogoutService", b =>
                {
                    b.HasOne("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("SingleLogoutServices")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Rsk.Saml.IdentityProvider.Storage.EntityFramework.Entities.ServiceProvider", b =>
                {
                    b.Navigation("ArtifactResolutionServices");

                    b.Navigation("AssertionConsumerServices");

                    b.Navigation("ClaimsMapping");

                    b.Navigation("SigningCertificates");

                    b.Navigation("SingleLogoutServices");
                });
#pragma warning restore 612, 618
        }
    }
}
